site_name: Orchard Core Documentation
theme:
  name: 'material'
  logo: 'docs/assets/images/orchard-logo.png'
  favicon: 'docs/assets/images/favicon.png'  
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'light blue'
  static_templates:
    - 404.html
    
extra:
  social:
    - type: 'leaf'
      link: 'https://www.fiveforty.fr'
    - type: 'github-alt'
      link: 'https://github.com/jpiquot/ExtenFlow'
    - type: 'twitter'
      link: 'https://twitter.com/ExtenFlow'

# Repository
repo_name: ExtenFlow
repo_url: https://github.com/jpiquot/ExtenFlow
edit_uri: edit/dev/src/

# Options
docs_dir: src

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.superfences
  - toc:
      permalink: true
#  - markdown.extensions.nl2br

plugins:
  - search
  - git-revision-date-localized
  
# Page tree
nav:
    - About ExtenFlow: README.md
    - Getting started: 
        - Create a ExtenFlow Web application: docs/getting-started/README.md
        - Create a Theme: docs/getting-started/theme.md
    - How-to guides: 
        - Follow the Guides: docs/guides/README.md
        - Create a modular application: docs/guides/create-modular-application-mvc/README.md
        - Install localization files: docs/guides/install-localization-files/README.md
        - Integrate Facebook plugins: docs/guides/integrate-facebook-plugins/README.md
        - Run code on startup: docs/guides/run-code-on-startup/README.md
        - Create a custom admin theme: docs/guides/create-admin-theme/README.md
    - Key Topics: 
        - Customize the Display: docs/topics/display/README.md
        - Localize your site: docs/topics/localize/README.md
        - Handle the Media: docs/topics/media/README.md
        - Navigate between pages: docs/topics/navigation/README.md
        - Query and Search data: docs/topics/search/README.md
        - Secure your application: docs/topics/security/README.md
        - Workflows: docs/topics/workflows/README.md
    - Reference: 
        - Core Modules: 
            - Identity: docs/reference/modules/ContentTypes/README.md
    - Glossary: docs/glossary/README.md
    
