name: ExtenFlow
extensions:
- name: dapr
registry: dapracr.azurecr.io
services:
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
- name: redis
  image: redis
  bindings:
    - port: 6973
- name: identity-actors
  project: ExtenFlow.Identity.Actors/ExtenFlow.Identity.Actors.csproj
- name: identity-services
  project: ExtenFlow.Identity.Services/ExtenFlow.Identity.Services.csproj
- name: identity-web
  project: ExtenFlow.Identity.Web/ExtenFlow.Identity.Web.csproj